export const LOAD_MAIN_START = 'LOAD_MAIN_START'
export const LOAD_MAIN_SUCCESS = 'LOAD_MAIN_SUCCESS'
export const LOAD_MAIN_FAILURE = 'LOAD_MAIN_FAILURE'

export const LOAD_PLAYERS_START = 'LOAD_PLAYERS_START'
export const LOAD_PLAYERS_SUCCESS = 'LOAD_PLAYERS_SUCCESS'
export const LOAD_PLAYERS_FAILURE = 'LOAD_PLAYERS_FAILURE'

export const SEARCH_PLAYERS = 'SEARCH_PLAYERS'

export const LOAD_GAMES_START = 'LOAD_GAMES_START'
export const LOAD_GAMES_SUCCESS = 'LOAD_GAMES_SUCCESS'
export const LOAD_GAMES_FAILURE = 'LOAD_GAMES_FAILURE'